export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const LOADING_REQUEST = 'LOADING_REQUEST';
export const SUBMIT_EXPENSES = 'SUBMIT_EXPENSES';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
